language: java

jdk:
- oraclejdk8

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test

env:
  global:
    - secure: "LR/9RUDkJicAkZ7wqGOob2fubg+2qTXQgm2UJ+HqI7CJ1hXB6v2OZKJqc/CwarA0b7joqAlDmHocluFnHKJWC+8eAOp74b1QBSwu+aND9zyEAJfkDGxDKqUoRJ0EME2EPelW8AjqXDb4/2DVzFsR3pDun0hkvorLZRmDqHez8OwFMm06iwNHdqylDDzZpIJRVmmbqe2/J92+1vEr51g4IJ8un+Kwxv8JvWNVjV0DagCDPQKsnXUH4WfEnVxP6u3ylBWUZl7FZZGkLx3NpzLG03OtSmFCsh5kuCV/qvv/dyO7ut8zOKxpIMyWh6coaPgmABnoYDM/Fj8TqwPzwuJdh3Hc83eunEXejaqvzeRQdp/p3Zd1NVzcVaD65fZ3GxQDTVBKp81OVQfSzqKxkScITlas7nFcEbWRwP7mbzOplCS9Tpvs5NRg59Atl+MP3qQD49C0EBl+XwBoZFYvSuenrqTaJ3nhZLrhAM8CoyIN7vSKHBg0uwGFOCwXG3a1/0StXWu36YpUznwcGOt8WaM+btnRTk+gFqYcBfnE8Wrt0EOBljZd+3yw1eelgWviAwcn/JvsfDokv/HMzo2Eug4LyBMsp+BtxpQq07y+EpCplR5BKrzpHl8hdwSVU7ds8G7W19tEYqS/kMu2soGhZNDL8HmQxk5CErc8tNHa7omKTAQ="
    - secure: "ufjGH1CBUqcdb+OVblV4pkNpmA7iaCt3u5BSvYtR03QgIPEop686PoSF2cGBmicNatzEDySaeLuRK74I/mY+GvkUBAyndUPibFyJaEkf2HWvIBXdn8ed7LhzcShgfh/N4vIxhi6R1DspOsKuyjW/jNRKzQHDYRhp79CrbF1K0X48RC1MSO0TpHrCnfjrreyvJOhWT8YhAG32nqokMu5TKh0zPtqv+2FtqG/WCwh5IiqRr2gF4Z1zFO1/Z5keLvHpixj6YQNOcMizj5fWOYqi2l6UW0Oz9yBOo+6aTA382WsGyxQV/xSawOjABLxYPWrbkMXWjl0KcAQYBKxosIAJkVVlZhP0Xq4k+0uFMavf/V09/RoXHkNy+Ec8xGDLL9HFPHGJaAJTpPqLorD2tjTHqKjAxYOyEYA/qRRaAcx4tSL0mda3N+dbGjvq9vv9dB5qLMz/DxnLVcBrsGeQpOZ/QlbDNXIkY4skBLjjWHfs+V9AYAS/imjyrJ0qH+IZkSCzGzMdUjWoCHkgK59hILVidXUD6Yzk6LPXz8wH2mAMbHiCDayXxw84A5Cp33lbhOFC9I4GQY5pMVJAXt2rl5Z10LQcX8x6CENhroDNeQCg0lj1TEKOSPFNqMmC6CKvN1v9f5bRbYkwe2viALPUOTjzc70P6Sm7WqxmoBwt3HxVH04="
    - secure: "Jz53uIGNsJihs831e3aTpUFT+5mtfjMakMYRLPQklmBE2M3eN2ZsRfC8fd/ydFe7tTN0Bq1Xny3cchC6XWii5wSawiO8q35xmcEm/GusTqHTOODHTEUSJSFBtR+Oh0L9j9ef1vvqjBYAToXAoUPYXoRz1HIT20shbKpNAhf32JyuywS+tA9CAMQ4nkMrjsSaYQum6J/wkSEVBCTHV8q6k/ombKjB+973j016xyn958qKEDHTbOi8osIbdVzjl1UkqxBtDISqSr044mdFguZKOsrbl8VdNdInGx2XGjkoCbBcQGSEdLOfji2jHzoWcDseuk1f7zfVmEcED/RT4SLHPq4fjcztc0hmNEUrF5AIofVuiRy2jf5fXnX34n67IlOqv7rSEt5qn9Anbu7XkUKscBbxjGAVuA8RBm11WXs4dbl0zfyK3rh04k/wDLXJY4F62xRVR4slNeReb7DRfDZE0IQIS8Ys846dXufsfJrIFgYWFHWA6KixWlJNBkCGvkqj4vScdCQ2O899PkZ+JSHtNVjvMOToNKR0ZE1gOD3E8ZQDIXY8rR71drgJ/fFQUSpGiZxwSRlF1BtvltbU0vYqetwAhhFw6wFuUj0icUrwu/kiGABuvO3aE09aJf8pw3JslHf3TNfTqKdkaSTdTN4ahPU6hGeLq3nc/AiR7TKxlqU="

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  file: "Yuk-Produktif-Reminder.war"
  on: master