language: java

jdk:
- oraclejdk8

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test

env:
  global:
    - secure: "RLOkTFTFV5Pw9g2vq1jh1Xulg5U3vdeyuYf8ye2lt7/X+nQ4b+E4+VQ+ONOPrgkKRx/IdNpWoGhkE5bNjQyraPqD5+q/xpp3thdveJebIwCNg11VymE9fpS3BYRCLRzMSyuLjMWiCj2XaSAtC/VKnGXDdSu4LVz6LVgG3lxwIAHyzlDObErGQq3QciLBpCSmuFAMg52hImcU6y9fQ91+3N4SVXXJd5+e92JvD3Zf5WDNyuWYxooFA7mTSsJ8GjTHx5rcneT6Hp116lya+ourO5Hg8D7C2RcfDI4xa0+3wbyMyvLuPYKz2yo2OodTagTRYqICCinOQBz606nPaYe+ROofZzGWrerMB5aEVy8+V0Tlrhb9NVDDXIaX5kHYZXl/jCGLDJTdmzLACz0QDTVpfZC0wPydKWk9sRmNaQads0rNB2Kwyb87RRfB7IZb9x197QZkhLaXk6y9m67Enlw78K3jdKEYIxhEuEbBelZCzvuSjI/t5yoNQ3JVWiB3+edPZR4zot0Cl9IEpt0AxxWbYfujQXQPz/uRc3oXkE90tkDCNjq3ehkXJLbdPTBl39HYFYG2+xHerHsPwe2djgQDu8yb7iC0+NLpQ/uiX0qG9Q0qvcMqF03xmLPhsGYtvr7FKAc9L1y7avFh2yX4/32VZr9+zSmyQ9dwyzcPq9Uf/NU="
    - secure: "qDhjJ09sMxS4rvWc0GlzCbX3VejrRQ++SsJf9fLEBF4hH4Xm14vq75xLTDE7ZKg0sGTash4OjJrJAjcvklEnTB+nmmfLoW5qw+9O+8WwiAl0ad9mqxn8v5tCCyF5CXIzSHNsw1gGjO9LMo9N47vXLpFUCKc78WKXOBOyQcIIOwpOJS8XeonpSzuy43NjJHvwE5Xjgjh5o9lkM141yUHTj9hiSnzG9OYScIViE3Sxxehf9U7rQnDm2cKOe3CYhB0DtoHnGgNDJXi+QzIG3msZLJM0ou/1cYRfkHJNUhLEmT1fy7Rewr0LUocO3nT/yQVgHvD+xvYopH0k1v9aN/ckN9rbrK3Mf7wpFH1EzMhDXnTMMQ5Ipf7DVlImtZBqphZ37XaE6HoGbJN2dBJIiCZ/0CC48oYfVI3S16S2GyU0siCYaDuMDjEEOd3UvCHuVXziQwVksMXR9W467JPln1Es1A8LQwEzq0X6+Gkf+Uo9ls4+Iu8aV7kvJeELBwCrBbNzh/1d6iC0mX/V2ysvBO7FAyPwN46FTNOyq5Tbh6qOgn1ZOlJsvH+IYZcWI7nowYesQKxMXAbzPh+sVJqBjMUy6dVuW1yp2iQ0Gbwvq077XzicOmN51LPjEQE23alSBMLvgxX9j2vnFbwcWSlDSFB3KHdxLEEZerBMjXOVz+t90uw="
    - secure: "Jz53uIGNsJihs831e3aTpUFT+5mtfjMakMYRLPQklmBE2M3eN2ZsRfC8fd/ydFe7tTN0Bq1Xny3cchC6XWii5wSawiO8q35xmcEm/GusTqHTOODHTEUSJSFBtR+Oh0L9j9ef1vvqjBYAToXAoUPYXoRz1HIT20shbKpNAhf32JyuywS+tA9CAMQ4nkMrjsSaYQum6J/wkSEVBCTHV8q6k/ombKjB+973j016xyn958qKEDHTbOi8osIbdVzjl1UkqxBtDISqSr044mdFguZKOsrbl8VdNdInGx2XGjkoCbBcQGSEdLOfji2jHzoWcDseuk1f7zfVmEcED/RT4SLHPq4fjcztc0hmNEUrF5AIofVuiRy2jf5fXnX34n67IlOqv7rSEt5qn9Anbu7XkUKscBbxjGAVuA8RBm11WXs4dbl0zfyK3rh04k/wDLXJY4F62xRVR4slNeReb7DRfDZE0IQIS8Ys846dXufsfJrIFgYWFHWA6KixWlJNBkCGvkqj4vScdCQ2O899PkZ+JSHtNVjvMOToNKR0ZE1gOD3E8ZQDIXY8rR71drgJ/fFQUSpGiZxwSRlF1BtvltbU0vYqetwAhhFw6wFuUj0icUrwu/kiGABuvO3aE09aJf8pw3JslHf3TNfTqKdkaSTdTN4ahPU6hGeLq3nc/AiR7TKxlqU="

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  file: "Yuk-Produktif-Reminder.war"
  on: master