language: java

jdk:
- oraclejdk8

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test

env:
  global:
    - secure: "mGVUsnPZskVitQDyxJUaJC3dhxU8wNuT0ardrpR6y9XrQbYLcspZv+FUDiaJl/RQ1KRJghCRsZ3A5RoJBmOILao27+h9nv4+uJAVLGPaevboPLRDY62KOBpHB+GkcszVvgMKgACyMftntnvPG9b0DfEgEb4PnFAFS8ba4UlOVlKR9aVOoPH44d30zD7EztBkC6mh/Fttvjs1YUykVt5aA4REvRTmYYtlvqKGPOl+l0kq9TlqyRVYyC+iQfVqclK5IwEr9PekGI7UFeQROqo3rLe5InVlue8vZNlAzi2pZTgzPuFqFRdG+V/FIVisADd2dcjM9uucYjmPLnK4O11rdQMcK2vWXWaXnVgkCsHHDxE9u1/GOC8D9akzqxV9FkqnrtRfrxtTgg5C1hgmbkrhYh0/sHxdrErTJ2CbF7JbwuI836aQNB5IkJ+R/Zk8yy7oAzDVKs8o0nZnA5ZdwiirI5BE21irpJz+EQNZWAtQLyQ629WzteuN52lT5/zwOBd0dov8FKcfYI6UhNr3gXiBN+MCSRpz09qoDr4no1+96SCsd42wr3HS6fmSbA/pfQF29sPSp3i4MRi38yPYcoaAUswcPVpkEwqDu3yvyRzTegUaTCwqoaJMz+IuYphO+a/uDEucXiDDNt6DMyMSzZBA/QBglJVc75VT69jmzBIMYi0="
    - secure: "ruEzFHtQuil6FGv28GE5/oGEukqZEQw9rK54cW5XNw25YHhLBAewlq7zWjPmkeLur20okAHYFG39ajd95Y6CKgjvkwC9nqMqcmxg5+81D/6lNVTIAmPvSlUC8r8d2u69G18/G57rXcajfu087AGsKCYkQO6xVvOJMXNsgBswN3VBDd6HZ/bPsZO1lDwSfPuNWgIWSMy7W1gjxTiFuVi+DraBJ71YRxqjXfGYH9ML0UAMdq8DWJvv72YlCYreFlUnFhhlogbJlzkySk+Fj0Bi+BAuNdxZvWJiehtvNytSGEASzubSycsbde3Ghijc8QbtQmYDlaKFrmDiIK8c3gaZfAyKCFsvtxrRQ6Yrh/4+GAcxZRbgA5J6FnPG7tKHfkqPFhfsZTIkeE0W7km/LZadhZYXXGE5dT8nLa5YxR3iXtMw6dTtbuOkGh/9lRmbrP0s5Rvqhz6MTwAlwlYtUxje1qCOXDlDDYWggh4LeUFtorzoDqK/dwc42Odu7kL2I4KWfuOX6Na2AWme+ttHO+Ks1DxTQZS+gzymxBExPbuf8l0xGy6Yth2uqVEGkmYSSrWyFInTCApKlOKj6wOjMo7cayIMaLc8r5nLThl4R9YgqcWVJgp6Qzfxe7eVbK2pKTCPuqUr5KINih+rXIAHMKtvtXtJQyfgc4O6RKK0zcDV9tw="
    - secure: "kB5DI4F/H1X7xR0lUv1gSKMNVnObl+pPtY832bJo5JmevrGZOue6yiq+75P12T4QD9aRkIaiLeGW2fbm1KzDAEWZVpVLIgwA4mUL+MJAd/Q2BaeLTkXUmMFcJSJX6W1g7jx7BKOX63yyb6tpjcNAQIlVRVJVfueRMqjP/i600/PWzb759SZCAtedwgXiEABgjz2gN9dvGreXJrzErBS6iWGznatlaN/a9dq7/Ns55vriyhdAA92V1mELoYdFtSKb3C2idgDbwc9w+vpTbkWTTse0OThZAU2V5VDjISFn4t+9kEywfm+AqA08sZv+qrnTBra8Z9YdO/uW01cYMkis+O+L9PFs1sWnJJA0rXBvkPvaKw+9sU2bAKd+5HYX+0eOB3Qe3JexlnOMcBUMsAXEzfN4fnYGSjdPCQmxMvLDUg/Za4wjk5efGoa58BF2AB1BbvAVNHvx7qHwo77OZrdmpfzVKuIH0b4z72lMbxnv1aXbnPeC0Fj8X83IoqZfp30sYavac6a9e67tk0E9LjSOSR1SYs25I8djxV+Jtt14gxzzCWxLVTm/BKa/dYtg3oS0joC16fVR00cblkIOJqJZK7Wgg9GqM2G8EBAkIsJq06rflt6ehNYasOzHB2XeVbbUKHpbMun2TQnjoWV4lQbBq1ttoKqOlLKBX6jYaiizh9U="

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  file: "Yuk-Produktif-Reminder.war"
  on: master