language: java

jdk:
- oraclejdk8

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test

env:
  global:
    - secure: "mGVUsnPZskVitQDyxJUaJC3dhxU8wNuT0ardrpR6y9XrQbYLcspZv+FUDiaJl/RQ1KRJghCRsZ3A5RoJBmOILao27+h9nv4+uJAVLGPaevboPLRDY62KOBpHB+GkcszVvgMKgACyMftntnvPG9b0DfEgEb4PnFAFS8ba4UlOVlKR9aVOoPH44d30zD7EztBkC6mh/Fttvjs1YUykVt5aA4REvRTmYYtlvqKGPOl+l0kq9TlqyRVYyC+iQfVqclK5IwEr9PekGI7UFeQROqo3rLe5InVlue8vZNlAzi2pZTgzPuFqFRdG+V/FIVisADd2dcjM9uucYjmPLnK4O11rdQMcK2vWXWaXnVgkCsHHDxE9u1/GOC8D9akzqxV9FkqnrtRfrxtTgg5C1hgmbkrhYh0/sHxdrErTJ2CbF7JbwuI836aQNB5IkJ+R/Zk8yy7oAzDVKs8o0nZnA5ZdwiirI5BE21irpJz+EQNZWAtQLyQ629WzteuN52lT5/zwOBd0dov8FKcfYI6UhNr3gXiBN+MCSRpz09qoDr4no1+96SCsd42wr3HS6fmSbA/pfQF29sPSp3i4MRi38yPYcoaAUswcPVpkEwqDu3yvyRzTegUaTCwqoaJMz+IuYphO+a/uDEucXiDDNt6DMyMSzZBA/QBglJVc75VT69jmzBIMYi0="
    - secure: "ruEzFHtQuil6FGv28GE5/oGEukqZEQw9rK54cW5XNw25YHhLBAewlq7zWjPmkeLur20okAHYFG39ajd95Y6CKgjvkwC9nqMqcmxg5+81D/6lNVTIAmPvSlUC8r8d2u69G18/G57rXcajfu087AGsKCYkQO6xVvOJMXNsgBswN3VBDd6HZ/bPsZO1lDwSfPuNWgIWSMy7W1gjxTiFuVi+DraBJ71YRxqjXfGYH9ML0UAMdq8DWJvv72YlCYreFlUnFhhlogbJlzkySk+Fj0Bi+BAuNdxZvWJiehtvNytSGEASzubSycsbde3Ghijc8QbtQmYDlaKFrmDiIK8c3gaZfAyKCFsvtxrRQ6Yrh/4+GAcxZRbgA5J6FnPG7tKHfkqPFhfsZTIkeE0W7km/LZadhZYXXGE5dT8nLa5YxR3iXtMw6dTtbuOkGh/9lRmbrP0s5Rvqhz6MTwAlwlYtUxje1qCOXDlDDYWggh4LeUFtorzoDqK/dwc42Odu7kL2I4KWfuOX6Na2AWme+ttHO+Ks1DxTQZS+gzymxBExPbuf8l0xGy6Yth2uqVEGkmYSSrWyFInTCApKlOKj6wOjMo7cayIMaLc8r5nLThl4R9YgqcWVJgp6Qzfxe7eVbK2pKTCPuqUr5KINih+rXIAHMKtvtXtJQyfgc4O6RKK0zcDV9tw="
    - secure: "blcSN8FCm/99qt+Q88q+vwnCIHfbn6ANyBab5ChJeYOdJPt8QtYQXnXZA8+reoTIj1R6LH/v6KKe+gIbg8UxdlbzS9gQ9T86XHe6dmDLQEXKxO12CQB2++NSViP6ZvVZJ9g2dccRmfuWI/Eoq+epxMPtrbfTA19jnoQ+G9EVccVtvQxka3KnHibqjMaYgDG2bo27R1ysJWW78Yu/0vpXrmdaj0mRTJhFQdhmdgFDGx19ZTotFI0Mr39NdaciSRO4yFSSjjw81KKKyNPuHyM4JgttesrbrgOf4THMYy1r3dBBO+f35cteqANACoEtMMuTVSrHK/WaBmwGF6s/+AfA8lV0Ye5rU9X2VgjQ3iW/u5+hShTtfCyYQYTV6jOe3mc6XwuZ2HUlI0n6Hlhq8M3Nd/BiENXFDUuOcHhwWD/6sGCuvB2xTFLEuthDIdaysRY+MVg8Ul+w3Lh6KHEiEHLMumssTz9KodAJ3DAFJPshA51/jk3ioRbNOSAoWxWBY4iH1lCERcfd2tXkWyepVm/7SOze0+8euUpqzbWkQQ/XqL4dMkP+XA0VewI9VPPEP/8YHQLugJhBsUyBvuHMnwsKGvP/TlwJrbALV/W0qBbfMgo3tSZ56pg11I5wX93n0BPtXVeFIKqLSAb3d5wKRJrnTCcdJuxJq6jmYQpLtnuGGHk="

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  file: "Yuk-Produktif-Reminder.war"
  on: master