language: java

jdk:
- oraclejdk8

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test

env:
  global:
    - secure: "k8j/YVuna6M7FfrQ6O4CmEX35su5hyY9sJCh9zMq2XEDEVLN7LQbJUj5EgZwHtkqvxsREQlU9zZ1VjObJD4FxZkpeeC/m9NE7ZhwW30zR0OqoRW5Ce7xk7dd6rHDe5jQfNPk22nmSdsrw+WJMO8aXlC016p1RelUR5YfZJjqZ1DTlqoaiIgaHAnTE0b6l8KdL4lLzaMjGR7BA/JVJJGxPMk4YS4eQ8mqy7Dv6BFk9f8E+GCqzDyoE1p2HcwQtB6WlttH0peGz+sysyj6wK/1/6x1XCtdZfsWwwqPJVHjZA2f/f6Iz72Mi7aaFrzdzksyjU1LXjV0g+9DkeW3JbLxpT/GuTngKkV5gceInoS0gKOBZsKTsJg9tq2wwYf+uWnQrqi0cSZA1bYvdAZ9h6D8C7F9s1Gli7p/fGnFAnyFb1k61CtNh/igfS5l4SofOe/g+GeIZi4mcXT4fYPfbzmHg/JBAVA1T2KFAjNX435DLqrKYBgf/CKpVnJ7v7eG7mH6LgRUiOUvFTJ8jpLGMbGHgkQgO/dC6K3gG32j4JK8uxs8sBLtyoZMHkNpXXtk3nJHnxi3foEEI9vzmPEN32bxKzULAZ0uduuWYesm4Ww58OgrllajTO3MV82EHT4BrCiGeRBVNtaeP4dkXl+b5X9H+znL2vymCp4u0SEv2T+ZQMw="
    - secure: "ruEzFHtQuil6FGv28GE5/oGEukqZEQw9rK54cW5XNw25YHhLBAewlq7zWjPmkeLur20okAHYFG39ajd95Y6CKgjvkwC9nqMqcmxg5+81D/6lNVTIAmPvSlUC8r8d2u69G18/G57rXcajfu087AGsKCYkQO6xVvOJMXNsgBswN3VBDd6HZ/bPsZO1lDwSfPuNWgIWSMy7W1gjxTiFuVi+DraBJ71YRxqjXfGYH9ML0UAMdq8DWJvv72YlCYreFlUnFhhlogbJlzkySk+Fj0Bi+BAuNdxZvWJiehtvNytSGEASzubSycsbde3Ghijc8QbtQmYDlaKFrmDiIK8c3gaZfAyKCFsvtxrRQ6Yrh/4+GAcxZRbgA5J6FnPG7tKHfkqPFhfsZTIkeE0W7km/LZadhZYXXGE5dT8nLa5YxR3iXtMw6dTtbuOkGh/9lRmbrP0s5Rvqhz6MTwAlwlYtUxje1qCOXDlDDYWggh4LeUFtorzoDqK/dwc42Odu7kL2I4KWfuOX6Na2AWme+ttHO+Ks1DxTQZS+gzymxBExPbuf8l0xGy6Yth2uqVEGkmYSSrWyFInTCApKlOKj6wOjMo7cayIMaLc8r5nLThl4R9YgqcWVJgp6Qzfxe7eVbK2pKTCPuqUr5KINih+rXIAHMKtvtXtJQyfgc4O6RKK0zcDV9tw="
    - secure: "qlrHI9JRrtAIyBWZkjr4Foz2tQZdeUflQqWedMdEpKz3Jubr0NzGrJOdsr/sgmY9ocjfdm9OvauSlDgRuDpSF2+rRUhs1V8OmOgglft5rsBs/WEJy57mND8kY0K7gwR8OFY8FOeiaCd5x0PThyLZcZxtL80dcDfic8TZvoyDViS8LlWlOvCw45EOXaPA0+i+9RVxIcTnjWVgZeRN8bWV3f6OsenF7cHukYZQKnv94s0ohJajmfj4gXXlrAYZiI5AlNzwUOeb+M7xIehN/aRIjQDdnZzXc1pXEpaGG4XJs6f7534jkULeS8xqVgnMGIkmNHCJQHGWjo3ajGxPF3c6MoAYZLLdl5XipIRI+1puQC9zxOeFWsU50Lt3temQBu805lRpbHfIP3hGlwMvc8isxvqOUev2c/35UNaI9qa4abH21OujWyh/kkZfD2yxFl5a56DD2L9JhXqMHEWy90lYc5Ihn9JR7SlFNWkPNbX2pBNauvibhM8PHCEXWqGOl5G75d7puLbhWQvfS+XJweqJTc7pdSH3ua4SKJtABDpsBcbUsGScK/Tq4VRSbeRYdjhgtOFmyO6W7H9YxboXryAQZ4+QhIxphJ8PJ86RqAmqFdbd6QdVoXVo6GzlUtJJYeUCWI1SLauCpkInVGygR8EFGtXXKylxtdPZADKGPiHKvAU="

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  file: "Yuk-Produktif-Reminder.war"
  on: master