language: java

jdk:
- oraclejdk8

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test

env:
  global:
    - secure: "d/JkoY5PT8wfZCQvWUgv75i48FjBm+G/cC0S+RVOB8qnNmE5dAzHqKewGrM2ZnGfpLI+0SLfFXBRG5YP4uwSbGic0CKvp24ssOyz1xLCGnQ2z59GmD1wbF9N8SBvWoMBLhIVsACK2yFUKyVA+oWg9BcEpm+VqdhxyYq32Ush+oxPrV9wE0kl4lqsR2hgPR5JNeE2lV/SJqyFCX48c97emUhuKbcmhZVzOrQtxm3VYT9F8aW4J2kghVdEeirPXPBG0bXAYRLOECZnDghOh2/QmTk2/zStAoqKQJuGZU7Qt1OW+DVntFd7XyCrWiEPNhWBbN8wMFUN7k4ccryt0eKA4cz8Mx3BRTgBhfKNvzSw6uBhEsbCQ78eu45o6pQF35Vhmyjp0v5UwOfqoWFmTyQ3SbyKMDqW+rcvIyAjOdE3OByGUuVUPjGNQ6r+PGvr2JhPXEVaA+2SjwABJZsAZTATfoL4U6jeGlw+QSzgq3vFfcPBiMVyYif0/YxdGG47wouCpXT01ItyWGJKmsq+rnKOtzJA4tyikXnXA26ndaadkdnGMdXuq8SJPAZ6J5y7K77GoSA4exjKugH5w6Ks0TyXiLK6C7rGWAs+fUIpXtbc0sdj8gJ9ENTxyzI/G3x/CDgBcw/Q/Tl/cglhV26lR3RCvyEH5B5tR9fuNPx8lw0qme8="
    - secure: "L7imCEd4Idnu4JXn1OXQRjks9gLE25IIJwRR5s4TWsJiuUclhLzHeZQ1oEwkMoRmQzP4cp290Q3H2oBeTZtUSZzaIEFTnp/ESq128rfvvJo7zmpPUQPHKZPwdwjfv1AeTvktFa+eGSZ3mtTsGv4RVAIlEFSbHB16c4RkfWpsrJ8MYe9dY0QDo51hHn46JkSkDJZ/D6uHpiEtSrPfH28o2bxfGbI2bsAbeI94mn+B7BDE96EmD753EyuwFU899ocZ/tkJe5Dk48m5X1ZPRL5G1GBaYzZmb6+5B9XgUsd+aJOqpbtQhNXvgQ4q+lI/+4w1hnwiWJ2b35NyvHpkXzJcKPi6aRqkaJXcfQIYBR99vdFeuMecMqOJ04vAUuyKhnJD/Va0Kc8vOkDrDzOSuDn8B3hQTRYHONoY6mKPXWXrhRSMMUqVP1ACJyGc4nR3CdttzeWkCMR5iqLl0E5fooAbJhm/Z3OuCn9ZPafxgBdFzSdsCta1MRggxjvcA5FAem9ZZZMxBA534tZNC+iI43/+0rSX/y1MQbRU08SjKBtV+IaKThMcfKkE7G8blD1oyPQ2qeNiRaXn53jyTH/cdlIbgVAeNeowKMfrlebz5JToVDPhHV209Aa+V71Foqg6hRPI3vvqttKpz5gw9+gNvOsz1vzkLkIaOvTCSrPeGIw7Dl4="
    - secure: "oM/hWKR7tUN9K0TVrQHqT0sgpO/YvyY0EueteAHaQShdBF3kotCJZgQ13rXLvJ+f5BW+X/OyjWs8c8wSvRbRUV65Efvoj9lJ8OAvHlVbhwXsT7SYkaiFzmId3kW7EhBTiFT77Ms4WtOfdUTgkEb6UIygF6H4vX4G3vtPrTXRndVOrUhvJJ4AtyxEY3MpQfEjEBqI6VONgr4wJF6edrb8kY9+3HrPTBSKXPfgGRzSIYlYl/6vZIYChteCfAH94HWxByh1p/clG+QOM8nPX6ZoMjx+R252TtZKch0Q8XIdRHiGcz+eLZg6S4t26cMDz03ceCb6gV6m1ZKWDqnzjbIn8ruMJyXqpt9gZ+EKWiVbvjErpDiwHADTAwXYpyYoYQVQyhsY847NA9d6wfl0DTVczv7V47QK9BYpoNOuj/GnnoTt3riJ38sJMW/m6jI5ALbBv1cCzef4XFilJlt5BQDu7uf6Kl6jz9Jorm1NqFQIzoMpXcDnl+mxWbJUamXWlCQzow9QsF/2o3Fgw2jivzCqaQRPF+ObxhMp8WnMF9Y+WhQCCGF3p8SSP3QxX3IK6qtzoObda18I6vVg9p+l2vSQ4TwGFZtwOGG8WTn4MhDLlKsC9l1lgrzXmYH0Am/PrtHtxc1fQb/rxv7HR0ywpiAZodP0CSouQ9opHdGcQdc48kk="

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  file: "Yuk-Produktif-Reminder.war"
  on: master