language: java
jdk:
- oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
deploy:
  provider: heroku
  app: yukproduktif-reminder
  api_key:
    secure: BN1gRwcLgpp8YvIhmVRV2NANkiu9bAwqPtFZTHcAg2DVi0wD5FaWAgSeRTXJcORmgaPrksjsv5u3dUm9ahf5kEH8dnP62er4nBqfrZB5n/+XKn69GzM69bKawtoMvSUg8zvRO5J07wQ2royvje9q/txUaTt3u2XbwXBG2Q6eCN89gQX/gfnBl3y+vXWFoCtaNegGYPWIgRgCZ0vmPxDI255HpMMW06nY1KZpF6M97MO29t8zCuJk+IjKWyjsxtktjEVmhCc6lFm4mrN+gq/5EWoWnZ8tsCGHNBRGPyY9icYQaMg3/ffHslxjGSV63lD7B/ECx+lFWLnD0nBuSDNMQUxFRyQrYK5pvZ37AtjCwhF7quJ2mmLsBd/6hbvWARjOMBNY6cD+VeWvQA08yslW7syEbwV1xOoX7v3vhIhhEdHedf2AyQ6ueiE6RrbWZ94E2L4ITuuh/CR1nl1lX2T5Cw/a171srTQmx7degUsIlo7Ubb5tU8WZK7VUGmI/H40/uCHnlw4u8z/NmCtffti7IEJsqZJ8vMSGzyzC71rTlQa8mfHdH/ccVF4Q0Ep0decofURZgRZigX8wG2EbeN448VYOBysZmecErcRHCgQYswSwGC6oq9dGQbhz7NSBf6bONmU3tVE9L5Wpz0IrkLpY6ItxJTL1+spd3jBHrNdhOEE=
