language: java

jdk:
- oraclejdk8

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test

env:
  global:
    - secure: "mGVUsnPZskVitQDyxJUaJC3dhxU8wNuT0ardrpR6y9XrQbYLcspZv+FUDiaJl/RQ1KRJghCRsZ3A5RoJBmOILao27+h9nv4+uJAVLGPaevboPLRDY62KOBpHB+GkcszVvgMKgACyMftntnvPG9b0DfEgEb4PnFAFS8ba4UlOVlKR9aVOoPH44d30zD7EztBkC6mh/Fttvjs1YUykVt5aA4REvRTmYYtlvqKGPOl+l0kq9TlqyRVYyC+iQfVqclK5IwEr9PekGI7UFeQROqo3rLe5InVlue8vZNlAzi2pZTgzPuFqFRdG+V/FIVisADd2dcjM9uucYjmPLnK4O11rdQMcK2vWXWaXnVgkCsHHDxE9u1/GOC8D9akzqxV9FkqnrtRfrxtTgg5C1hgmbkrhYh0/sHxdrErTJ2CbF7JbwuI836aQNB5IkJ+R/Zk8yy7oAzDVKs8o0nZnA5ZdwiirI5BE21irpJz+EQNZWAtQLyQ629WzteuN52lT5/zwOBd0dov8FKcfYI6UhNr3gXiBN+MCSRpz09qoDr4no1+96SCsd42wr3HS6fmSbA/pfQF29sPSp3i4MRi38yPYcoaAUswcPVpkEwqDu3yvyRzTegUaTCwqoaJMz+IuYphO+a/uDEucXiDDNt6DMyMSzZBA/QBglJVc75VT69jmzBIMYi0="
    - secure: "ruEzFHtQuil6FGv28GE5/oGEukqZEQw9rK54cW5XNw25YHhLBAewlq7zWjPmkeLur20okAHYFG39ajd95Y6CKgjvkwC9nqMqcmxg5+81D/6lNVTIAmPvSlUC8r8d2u69G18/G57rXcajfu087AGsKCYkQO6xVvOJMXNsgBswN3VBDd6HZ/bPsZO1lDwSfPuNWgIWSMy7W1gjxTiFuVi+DraBJ71YRxqjXfGYH9ML0UAMdq8DWJvv72YlCYreFlUnFhhlogbJlzkySk+Fj0Bi+BAuNdxZvWJiehtvNytSGEASzubSycsbde3Ghijc8QbtQmYDlaKFrmDiIK8c3gaZfAyKCFsvtxrRQ6Yrh/4+GAcxZRbgA5J6FnPG7tKHfkqPFhfsZTIkeE0W7km/LZadhZYXXGE5dT8nLa5YxR3iXtMw6dTtbuOkGh/9lRmbrP0s5Rvqhz6MTwAlwlYtUxje1qCOXDlDDYWggh4LeUFtorzoDqK/dwc42Odu7kL2I4KWfuOX6Na2AWme+ttHO+Ks1DxTQZS+gzymxBExPbuf8l0xGy6Yth2uqVEGkmYSSrWyFInTCApKlOKj6wOjMo7cayIMaLc8r5nLThl4R9YgqcWVJgp6Qzfxe7eVbK2pKTCPuqUr5KINih+rXIAHMKtvtXtJQyfgc4O6RKK0zcDV9tw="
    - secure: "3YSTNfWbK83ilrtyq9LDaQwtTCmX9GoZTBVDhvxLSdNOt+m8QGnS7T0rmodh6gP7m64KShAVwwsvzsWpsYuP2FKV/QAeue5ORbML1k9GudfFjLzIHpGC272IZENYlEzm17IEaL5knvpvaR7k8lpVeSc8zz8fo3hMDECReXLKUM3yrlXeZihK5V235+9IQ6vn9VTOe/NV1UQXevCe/WuarZ4P8F1RXZENVocGCvno3oNQ7zlX4l67Q/m/H8VD+2G4sCiqxoMr0QCettewxzylrDCrgHcrsdVNtdVXCeH9+JGB3XYLa2OWBgxAU5dE4v4vrAwuth4WvaV4ubflvkv7o1nBtbBC4806+pZ6ZDlMSNWbKcleG+65oXbeoV1f0sJqlt3Jezt3CYfzVSm3Ve9FMRsAf/9ohXT/91HZmD5sCBMzKexPjhrA8f5SNLxBoMelJXmOHT2X7Lj6+jT6aatruT8XewE79hp3Il6V5+9FvKaSOimew4/pLNrZLgBQHYUBgwumJux3FnIgSIyjmXm0QlKqI91NO8O3ua0KMgWMajFdE3uD9p7dUU+q9swDE7gVaxOOHyghpg+Fjkm9ZFRuuCABCRPKVuNfmRLNDCgnYiO8jbXhixuBk9yuwjL0/N0utSUcAr5Qe0HgZqGEuGVsWYfq2w8rj2u125Ykb/XnuAw="

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  file: "Yuk-Produktif-Reminder.war"
  on: master