language: java
jdk:
- oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
deploy:
  provider: heroku
  app: yukproduktif-reminder
  api_key:
    secure: bUEvl2zUfjOGWnPu6yQtqK5GPa96457wPcuimHqPIANeRVMi0yHM8Pj8UxnH1qTSyUxxyasQ8ljd0N4xiZo3Q5eMr7i+jxhW1JlNnfDpP+5U+G2kNC+KlqrhNFCDdJT7FH3kA3VDY28BPzZEB65uK/YkhgtphwXweo3u1KGLVWVz0ZccwhX8I/iqPCSXz74sg8SCtIu2nicXTYmap95TB4bg8aIZsLU6X44di2nEWZV0/3OgiYWQqglWB/smZvGMNI2R5i9A/ddTaOygEVt0ifFGaNYmifuam/7VZeqY2kvCRel48lO2EiuuxUe++1AnpkRONb2aSnb08OxObse+dNjLLIa44UrP2L/yW5PZS2qzj3bNsoZOOEGLE+ZsKi/HR5oldeMp5UrHiAJYf+51ZBX4zVONWNTpZdcD3RWU3M+1ZbBOy46yrVEcAVYHpWbbARHlkpnce0fBJsQcQYF1jp75LtbFh6mS9ToqhMPY+Krnw0Xm7EuXrmlkmszy39blMwNDsXaw93e1xozTx58Bw89KcP3egkidnhpIVQ2mJlQauCNYQ1GUdR1facaKqc/WbNTwE8Vs7b8+oO03OY48KfS2Od91SDGd4lFW3MQo2DqOdENUeY5/N1G3LacVmQ+6piziT9TXbQzHJDda3jLRCEzHVqM3CmIvhH9YBWWTejs=
